name: Build and Push DevContainer Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.devcontainer/Dockerfile'
      - '.devcontainer/docker-compose.yml'
      - '.github/workflows/build-devcontainer.yml'
      - '.devcontainer/post-create.sh'
      - '.devcontainer/post-setup.sh'
  workflow_dispatch: # Allow manual trigger

# Only allow specific users or manual triggers to actually build
# Others' pushes will be skipped

env:
  REGISTRY: ghcr.io
  # Convert repository name to lowercase for Docker registry compatibility
  IMAGE_NAME: ${{ github.repository_owner }}/sse_group_project/devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only run if: manually triggered OR pushed by fengyuan213 OR specific commit message contains [build]
    if: |
      github.actor == 'fengyuan213' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[build]')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

